version: '3'

services:
  node-app:
    build: .
    container_name: cyb-back-end
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    container_name: cyb-mongodb
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017' 
    volumes:
      - ./data/db:/data/db
    networks:
      - node-network

  minio:
    container_name: cyb-minio
    image: "minio/minio:RELEASE.2022-04-29T01-27-09Z"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    user: 1000:1000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/image_storage:/data
    command: server /data --console-address ":9001"
    networks:
      - node-network
  
  # mc:
  #   image: minio/mc:latest
  #   container_name: cyb-mc
  #   depends_on:
  #   - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host rm local;
  #     /usr/bin/mc config host add --quiet --api s3v4 local http://cyb-minio:9000 ${MINIO_ADMIN} ${MINIO_PASSWORD};
  #     /usr/bin/mc rb --force local/${MINIO_BUCKET_NAME}/;
  #     /usr/bin/mc mb --quiet local/${MINIO_BUCKET_NAME}/;
  #     /usr/bin/mc anonymous set public local/${MINIO_BUCKET_NAME};
  #     "
  #   networks:
  #     - node-network

networks:
  node-network:
    driver: bridge
