version: '3'

services:
  node-app:
    build: .
    container_name: cyb-back-end
    image: node-app
    container_name: backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    container_name: cyb-mongodb
    image: mongo:4.2.1-bionic
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    networks:
      - node-network

  minio:
    container_name: cyb-minio
    image: "minio/minio:RELEASE.2022-04-29T01-27-09Z"
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    user: 1000:1000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/image_storage:/data
    command: server /data --console-address ":9001"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
